### ISSUE TITLE
Simple example?

### ISSUE THREAD

**Issue by ghost** [ApoorvaJ/EasyTab#1]
Cool project you started here! :)

Can you make a simple app that can be used to test tablets, like `xev` or `xinput test` on Linux, but for your library?

Thanks in advance!

**Comment by ApoorvaJ** [comment]
Thanks for checking the project out. :)

At least for now, I'm not really thinking about creating an example app, because of the following reasons:
1. Library integration is simple, and consists of only 3 function calls.
2. The easytab.h file contains documentation and short examples.
3. It would be difficult to make a no-dependency example.
4. I'd have to create one example per platform, and then maintain all these examples as the library evolves.
5. If you want an actual project that uses the lib, you can look at [Papaya](https://github.com/ApoorvaJ/Papaya) - my open source image editor project. Here's the [windows code](https://github.com/ApoorvaJ/Papaya/blob/master/src/win32_papaya.cpp), and here's [linux](https://github.com/ApoorvaJ/Papaya/blob/master/src/linux_papaya.cpp).
6. I've been talking to a friend who is potentially interested in integrating EasyTab into his SDL-based project. So the API may change a bit, and I don't want to spend time maintaining the examples rather than the library itself.

Hope this makes sense. If you have any specific questions or difficulties during integration, please let me know.
